project_name: jira-flow
builds:
  - id: "jiraflow"
    main: ./cmd/app/main.go
    binary: jiraflow
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - 386
      - arm64
    hooks:
      pre: go mod tidy

  - id: "commitmsg"
    main: ./hooks/commitmsg.go
    binary: commitmsg
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - 386
      - arm64

archives:
  - id: jiraflow
    builds:
      - jiraflow
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: commitmsg
    builds:
      - commitmsg
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: JaleelB
    name: jira-flow
