import { BEGIN_MARKER, END_MARKER, MANAGED_BLOCK_VERSION } from "./hook-markers";

/**
 * Owned `commit-msg` hook script generation (architecture §15-16.1).
 *
 * The generated file contains only a shell shebang and the JiraFlow managed
 * block. The block:
 *
 *  - prefers the absolute captured binary path (GUI/IDE environments with
 *    incomplete PATH)
 *  - falls back to `command -v jira-flow` so a moved/upgraded installation
 *    recovers
 *  - becomes a no-op when neither is available: a missing JiraFlow
 *    executable must never block a Git commit (ADR-0005/O-02)
 *
 * Paths are emitted POSIX-style with `/` separators so Git for Windows can
 * execute the hook through its shell (architecture §15).
 */

export interface OwnedHookScriptOptions {
  /** Absolute path to the compiled jira-flow binary, when known. */
  binaryPath: string | null;
}

export function generateManagedBlock(options: OwnedHookScriptOptions): string {
  const lines: string[] = [];
  lines.push(BEGIN_MARKER);
  lines.push("# JiraFlow managed commit-msg integration.");
  if (options.binaryPath !== null) {
    lines.push(`JIRAFLOW_BIN=${shellQuote(toPosixPath(options.binaryPath))}`);
    lines.push("");
    lines.push('if [ -x "$JIRAFLOW_BIN" ]; then');
    lines.push('  "$JIRAFLOW_BIN" hook commit-msg "$1" || exit $?');
    lines.push("elif command -v jira-flow >/dev/null 2>&1; then");
    lines.push('  jira-flow hook commit-msg "$1" || exit $?');
    lines.push("fi");
  } else {
    lines.push("if command -v jira-flow >/dev/null 2>&1; then");
    lines.push('  jira-flow hook commit-msg "$1" || exit $?');
    lines.push("fi");
  }
  lines.push(END_MARKER);
  return lines.join("\n");
}

export function generateOwnedHookScript(options: OwnedHookScriptOptions): string {
  return `#!/bin/sh\n\n${generateManagedBlock(options)}\n`;
}

/**
 * Proves that a complete hook is byte-for-byte generated by JiraFlow while
 * allowing the captured executable path to differ from the current process.
 * This is used by remove after package-manager upgrades move the binary.
 */
export function isGeneratedOwnedHook(content: string): boolean {
  if (content === generateOwnedHookScript({ binaryPath: null })) return true;

  const lines = content.split("\n");
  const assignmentIndex = lines.findIndex((line) => line.startsWith("JIRAFLOW_BIN="));
  if (assignmentIndex === -1) return false;
  const quoted = lines[assignmentIndex]?.slice("JIRAFLOW_BIN=".length);
  if (quoted === undefined || !isValidShellSingleQuotedValue(quoted)) return false;

  const placeholder = "__JIRAFLOW_CAPTURED_PATH__";
  const expected = generateOwnedHookScript({ binaryPath: placeholder }).split("\n");
  lines[assignmentIndex] = `JIRAFLOW_BIN=${shellQuote(placeholder)}`;
  return lines.length === expected.length && lines.every((line, index) => line === expected[index]);
}

/** Single-quote escaping for POSIX shell assignments. */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function isValidShellSingleQuotedValue(value: string): boolean {
  if (!value.startsWith("'") || !value.endsWith("'")) return false;
  let index = 1;
  const end = value.length - 1;
  while (index < end) {
    if (value[index] !== "'") {
      index += 1;
      continue;
    }
    if (value.slice(index, index + 4) !== `'\\''`) return false;
    index += 4;
  }
  return index === end;
}

/** Normalizes Windows separators to `/` for shell consumption. */
export function toPosixPath(path: string): string {
  return path.replaceAll("\\", "/");
}

export const HOOK_COMMAND = "hook commit-msg";

export const BLOCK_VERSION = MANAGED_BLOCK_VERSION;
